Fase1 023 - Consulta de todas las transacciones de un usuario
carolinapatino/MrPostel.Front pull request #18
Opened 2020-05-26 05:39 UTC by carolinapatino

## Propósito

Generar un datatable con todos los envíos realizados por un usuario.

### Tareas elaboradas

- Data Table con los datos obtenidos desde BE

## Características

- Historia de usuario asociada: FASE1-023
- Cantidad de rutas asociadas a esta funcionalidad: 1
- Dependencias agregadas (opcional):

2020-05-26 19:59 UTC, albasanchez requested changes

2020-05-26 19:59 UTC, albasanchez commented on README.md
> +<<<<<<< HEAD
Aqui se quedaron unos conflictos de merge jajajaj
Aceptar current changes

2020-05-26 23:34 UTC, albasanchez approved these changes

2020-05-27 01:10 UTC, vanessanadal approved these changes

2020-05-27 02:48 UTC, merged