FASE1-001: Registro y Login federado con Google
carolinapatino/MrPostel.Front pull request #19
Opened 2020-05-27 02:22 UTC by vanessanadal

## Propósito

Permitir al usuario registrarse e iniciar sesion con Google.

### Tareas elaboradas

-Se integro y configuro Firebase en la aplicacion.
-Se creo metodo federatedSignUp en el store que realiza la llamada al proveedor de Google, para luego registrar o loggear al usuario.
-Se hicieron las validaciones necesarias.

## Características

- Historia de usuario asociada: 001
- Cantidad de rutas asociadas a esta funcionalidad: 3
- Dependencias agregadas (opcional): Firebase

2020-05-27 14:12 UTC, carolinapatino approved these changes

2020-05-27 14:16 UTC, albasanchez requested changes

2020-05-27 14:16 UTC, albasanchez commented on src/firebase.ts
> +const firebaseConfig = {
Colocar en el .env todos estos valores (apiKey, authDomain, databaseURL, projectId, storageBucket, messaginSenderId, appId)

2020-05-27 14:51 UTC, albasanchez requested changes

2020-05-27 14:51 UTC, albasanchez commented on src/store/modules/userModule.ts
> +        .catch((error) => {
Quitar el .catch completo con el console.log

2020-05-27 14:51 UTC, albasanchez commented on src/store/modules/userModule.ts
> +      }).catch((error) => {
Quitar el .catch completo con el console.log

2020-05-27 14:51 UTC, albasanchez commented on src/store/modules/userModule.ts
> +            console.log(response.data);
Quitar el console.log

2020-05-28 01:57 UTC, albasanchez approved these changes

2020-05-28 13:24 UTC, merged