FASE1-009: Recuperacion de contraseña
carolinapatino/MrPostel.Front pull request #6
Opened 2020-05-17 18:39 UTC by vanessanadal

## Propósito

Permitir a los usuarios recuperar su contraseña mediante el envio de una nueva.

### Tareas elaboradas

- Creacion de vista RecoverPassword para ingresar el email
- Validacion de los campos
- Se elaboro recorrido de ida y vuelta al back. Para esto se crearon metodos SearchRoute,  RecoverPassword, y la ruta RecoverPasswordRoute.
- Se implemento la internacionalizacion en la vista.

## Características

- Historia de usuario asociada: FASE1-009
- Cantidad de rutas asociadas a esta funcionalidad: 1
- Dependencias agregadas (opcional): N,A

2020-05-18 11:53 UTC, albasanchez requested changes
Quedo excelente! Sólo hay unos detalles que arreglar.
Adicional a esto quitar los comentarios y console.log

2020-05-18 11:53 UTC, albasanchez commented on src/store/modules/userModule.ts
> +    route: [],
Eliminar route

2020-05-18 11:53 UTC, albasanchez commented on src/views/recoverPassword.vue
> +<template>
Cambiar nombre del archivo, los componentes inician con mayúscula

2020-05-18 11:53 UTC, albasanchez commented on src/store/modules/userModule.ts
> +    createUserRoute: async function (context: any, user: {}) {
Eliminar rastros de createUser

2020-05-18 11:53 UTC, albasanchez commented on src/services/userService.ts
> +  createUserRoute(user: {}) {
Eliminar rastros de createUser

2020-05-21 10:08 UTC, carolinapatino commented
Esta brutal! Sólo cambiaría las letras del botón _recover password_ a negro, para mejor visibilidad

2020-05-21 10:08 UTC, carolinapatino approved these changes

2020-05-22 15:40 UTC, albasanchez approved these changes

2020-05-22 15:50 UTC, merged