FASE1-003: Registro no federado
carolinapatino/MrPostel.Front pull request #7
Opened 2020-05-17 20:22 UTC by vanessanadal

## Propósito

Permitir a los clientes crear su usuario en la aplicacion

### Tareas elaboradas

-Creacion de la vista SignUp
-Validacion de los campos
-Creacion de ruta al back end.
-Creacion de metodos a searchRoute y createUserRoute para enviar los datos al back end.
-Implementacion de la internacionalizacion en la vista

## Características

- Historia de usuario asociada:FASE1-003
- Cantidad de rutas asociadas a esta funcionalidad: 1
- Dependencias agregadas (opcional): N.A

2020-05-18 12:40 UTC, albasanchez requested changes
Quitar comentarios, console.log y aplicar cambios. Visualmente perfecto!

2020-05-18 12:40 UTC, albasanchez commented on src/services/userService.ts
> +    .then(function (response){
Eliminar .then y .catch de aquí

2020-05-18 12:40 UTC, albasanchez commented on src/store/modules/userModule.ts
> +    route: [],
Eliminar route

2020-05-18 12:40 UTC, albasanchez commented on src/views/SignUp.vue
> +                                        <v-col cols="12" sm="10"><v-checkbox
No estoy muy segura de dejar este checkbox

2020-05-18 12:40 UTC, albasanchez commented on src/views/SignUp.vue
> +            this.$store
Cambiar por:
this.$store
        .dispatch("user/createUserRoute", this.user)
        .then(() => {
          this.snackbar = true;
          setTimeout(() => {
            this.changePage("Home");
          }, 1000);
        })
        .catch(() => {
          this.snackbarError = true;
        });

2020-05-20 10:15 UTC, albasanchez approved these changes

2020-05-21 10:20 UTC, carolinapatino requested changes
Esta bello!! Agregaría los siguientes cambios: 
Phone_number: lo colocaría de tipo number, porque actualmente me deja ingresar texto. 

Mensaje de error: Intenté registrarme con un un correo registrado, y me salia un mensaje de error, sin embargo sugiero que el mensaje diga Usuario Registrado, o algo que me indique ese error.

2020-05-21 10:25 UTC, carolinapatino commented
También vi un arreglo que contiene los idiomas, y un if para setear su ID. No podríamos hacer esto con una consulta a la tabla mp_language? En caso, de agregar más idiomas, se muestren automáticamente.

2020-05-21 10:29 UTC, carolinapatino requested changes
Podemos validar también que la persona que se registre no diga que nació hoy, podemos poner un mínimo, como que tenga 18 años para ello sería colocar la regla que la fecha no sea mayor a 01/01/2002, o también poner el current date - 18 años cualquier forma me parece bien.

2020-05-22 13:13 UTC, carolinapatino approved these changes

2020-05-22 14:27 UTC, merged